import type { Metadata } from "next";
import { Inter, Lora, Source_Sans_3 } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const title = Lora({ subsets: ["latin"], variable: "--font-title" });
const body = Source_Sans_3({ subsets: ["latin"], variable: "--font-default" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${title.variable} ${body.variable} ${inter.className}`}>{children}</body>
    </html>
  );
}
